config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users

    resources :friendships

    resources :challengers

    resources :challenges

    resources :places

    resources :activities

    resources :activity_types

    resources :team_members

    resources :teams
  end

  devise_for :logins, controllers: {
      sessions: 'login/sessions',
      registrations: 'login/registrations',
      passwords: 'login/passwords'
  }

  resources :activities
  resources :challenges
  resources :users, :except => [:index, :delete]
  resources :places, :except => [:edit, :update, :delete]
  resources :friendships, :except => [:new, :update]
  resources :teams
  resources :team_members, :except => [:index, :new, :create, :edit, :update]
  get 'team_member/new/:id' => 'team_members#new', as: 'new_team_member'
  post 'team_member/new/:id' => 'team_members#create', as: 'team_members'
  resources :challengers, :except => [:index, :new, :create, :edit, :update]
  get 'challenger/new/:id' => 'challengers#new', as: 'new_challenger'
  post 'challenger/new/:id' => 'challengers#create', as: 'challengers'

  get 'search' => 'welcome#search', as: 'search'
  get 'dashboard' => 'users#dashboard', as: 'dashboard'
  get 'livefeed' => 'welcome#livefeed', as: 'livefeed'
  get 'leaderboards' => 'welcome#leaderboards'
  get 'popular_sports' => 'welcome#popular_sports'
  get 'popular_places' => 'welcome#popular_places'
  get 'about' => 'welcome#about'
  get 'privacy' => 'welcome#privacy'
  get 'contact' => 'welcome#contact'
  get 'access_denied' => 'welcome#access_denied', as: 'access_denied'
  get 'not_found' => 'welcome#not_found', as: 'not_found'

  root 'welcome#index'

end

app/models/team_member.rb
class TeamMember < ActiveRecord::Base
  belongs_to :user
  belongs_to :team

  validates :user_id, :team_id, presence: true
end

app/controllers/Admin/team_members_controller.rb
class Admin::TeamMembersController < AdminController
  before_action :set_team_member, only: [:show, :edit, :update, :destroy]

  def index
    @team_members = TeamMember.all
    respond_with(@team_members)
  end

  def show
    respond_with(@team_member)
  end

  def new
    @team_member = TeamMember.new
    respond_with(@team_member)
  end

  def edit
  end

  def create
    @team_member = TeamMember.new(team_member_params)
    @team_member.save
    respond_with(@team_member)
  end

  def update
    @team_member.update(team_member_params)
    respond_with(@team_member)
  end

  def destroy
    @team_member.destroy
    respond_with(@team_member)
  end

  private
    def set_team_member
      @team_member = TeamMember.find(params[:id])
    end

    def team_member_params
      params.require(:team_member).permit(:team_id, :user_id, :status, :date)
    end
end

app/controllers/team_members_controller.rb
class TeamMembersController < ApplicationController
  respond_to :html, :json
  before_action :set_team_member, only: [:show, :destroy]

  def show
    @team_member.status = 1
    @team_member.date = Time.now
    @team_member.save
    @event = Event.new(user_id: @current_user.id, object_type: 5, object_id: @team_member.id, action: "#{@current_user.name} joined a team!")
    @event.save
    redirect_to teams_path
  end

  def new
    session[:return_to] ||= request.referer
    @team = Team.find(params[:id])
    @team_member = TeamMember.new
    @team_member.team_id = params[:id]
    respond_with(@team_member)
  end

  def create
    @team = Team.find(params[:id])
    @team_member = TeamMember.new(team_member_params)
    @team_member.team_id = params[:id]
    @team_member.status = 0
    @team_member.save

    if @team_member.save
      redirect_to session.delete(:return_to)
      return nil
    else
      render :action => :new
      return nil
    end
  end

  def destroy
    team = Team.find(@team_member.team_id)
    @team_member.destroy
    redirect_to teams_path
  end

  private
    def set_team_member
      @team_member = TeamMember.find(params[:id])
    end

    def team_member_params
      params.require(:team_member).permit(:team_id, :user_id)
    end
end

app/helpers/team_members_helper.rb
module TeamMembersHelper
end

app/views/team_members/_form.html.erb
<%= form_for(@team_member) do |f| %>
    <% if @team_member.errors.any? %>
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <strong>Errors!</strong>
      <ul>
        <% @team_member.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

  <div class="form-group">
    <%= f.label :team_id, class: 'form-label' %>
    <%= f.select :team_id, {@team.name => @team.id}, {}, disabled: true, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :user_id, class: 'form-label' %>
    <%= f.select :user_id, User.all.reject{|u| @team.isMember?(u) || @team.isPendingMember?(u)}.collect{|u| [u.name,u.id]}, {:prompt => "- Select Athlete -"}, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit nil, class: 'btn btn-primary' %>
    <%= link_to 'Back', edit_team_path(@team), class: 'btn btn-default' %>
  </div>
<% end %>

app/views/team_members/edit.html.erb
<h1>Editing team_member</h1>

<%= render 'form' %>

<%= link_to 'Show', @team_member %> |
<%= link_to 'Back', team_members_path %>

app/views/team_members/index.html.erb
<h1>Listing team_members</h1>

<table>
  <thead>
    <tr>
      <th>Team</th>
      <th>User</th>
      <th>Status</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @team_members.each do |team_member| %>
      <tr>
        <td><%= team_member.team_id %></td>
        <td><%= team_member.user_id %></td>
        <td><%= team_member.status %></td>
        <td><%= team_member.date %></td>
        <td><%= link_to 'Show', team_member %></td>
        <td><%= link_to 'Edit', edit_team_member_path(team_member) %></td>
        <td><%= link_to 'Destroy', team_member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Team member', new_team_member_path %>

app/views/team_members/new.html.erb
<div class="page-header">
  <h2><i class="glyphicon glyphicon-user"></i> Add Team Member</h2>
</div>

<%= render 'form' %>

app/views/team_members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team:</strong>
  <%= @team_member.team_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @team_member.user_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @team_member.status %>
</p>

<p>
  <strong>Date:</strong>
  <%= @team_member.date %>
</p>

<%= link_to 'Edit', edit_team_member_path(@team_member) %> |
<%= link_to 'Back', team_members_path %>