config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users

    resources :friendships

    resources :challengers

    resources :challenges

    resources :places

    resources :activities

    resources :activity_types

    resources :team_members

    resources :teams
  end

  devise_for :logins, controllers: {
      sessions: 'login/sessions',
      registrations: 'login/registrations',
      passwords: 'login/passwords'
  }

  resources :activities
  resources :challenges
  resources :users, :except => [:index, :delete]
  resources :places, :except => [:edit, :update, :delete]
  resources :friendships, :except => [:new, :update]
  resources :teams
  resources :team_members, :except => [:index, :new, :create, :edit, :update]
  get 'team_member/new/:id' => 'team_members#new', as: 'new_team_member'
  post 'team_member/new/:id' => 'team_members#create', as: 'team_members'
  resources :challengers, :except => [:index, :new, :create, :edit, :update]
  get 'challenger/new/:id' => 'challengers#new', as: 'new_challenger'
  post 'challenger/new/:id' => 'challengers#create', as: 'challengers'

  get 'search' => 'welcome#search', as: 'search'
  get 'dashboard' => 'users#dashboard', as: 'dashboard'
  get 'livefeed' => 'welcome#livefeed', as: 'livefeed'
  get 'leaderboards' => 'welcome#leaderboards'
  get 'popular_sports' => 'welcome#popular_sports'
  get 'popular_places' => 'welcome#popular_places'
  get 'about' => 'welcome#about'
  get 'privacy' => 'welcome#privacy'
  get 'contact' => 'welcome#contact'
  get 'access_denied' => 'welcome#access_denied', as: 'access_denied'
  get 'not_found' => 'welcome#not_found', as: 'not_found'

  root 'welcome#index'

end

app/models/challenger.rb
class Challenger < ActiveRecord::Base
  belongs_to :user
  belongs_to :challenge
end

app/controllers/Admin/challengers_controller.rb
class Admin::ChallengersController < AdminController
  before_action :set_challenger, only: [:show, :edit, :update, :destroy]

  def index
    @challengers = Challenger.all
    respond_with(@challengers)
  end

  def show
    respond_with(@challenger)
  end

  def new
    @challenger = Challenger.new
    respond_with(@challenger)
  end

  def edit
  end

  def create
    @challenger = Challenger.new(challenger_params)
    @challenger.save
    respond_with(@challenger)
  end

  def update
    @challenger.update(challenger_params)
    respond_with(@challenger)
  end

  def destroy
    @challenger.destroy
    respond_with(@challenger)
  end

  private
    def set_challenger
      @challenger = Challenger.find(params[:id])
    end

    def challenger_params
      params.require(:challenger).permit(:challenge_id, :user_id, :status)
    end
end

app/controllers/challengers_controller.rb
class ChallengersController < ApplicationController
  respond_to :html, :json
  before_action :set_challenger, only: [:show, :destroy]

  def show
    @challenger.status = 1
    @challenger.save
    @event = Event.new(user_id: @current_user.id, object_type: 4, object_id: @challenger.id, action: "#{@current_user.name} accepted a challenge!")
    @event.save
    redirect_to challenges_path
  end

  def new
    session[:return_to] ||= request.referer
    @challenge = Challenge.find(params[:id])
    @challenger = Challenger.new
    respond_with(@challenger)
  end

  def create
    @challenge = Challenge.find(params[:id])
    @challenger = Challenger.new(challenger_params)
    @challenger.challenge_id = params[:id]
    @challenger.status = 0
    @challenger.save

    if @challenger.save
      redirect_to session.delete(:return_to)
      return nil
    else
      render :action => :new
      return nil
    end
  end

  def destroy
    challenge = Challenge.find(@challenger.challenge_id)
    @challenger.destroy
    redirect_to challenges_path
  end

  private
    def set_challenger
      @challenger = Challenger.find(params[:id])
    end

    def challenger_params
      params.require(:challenger).permit(:challenge_id, :user_id, :status)
    end
end

app/helpers/challengers_helper.rb
module ChallengersHelper
end

app/views/Admin/challengers/_form.html.erb
<%= form_for(@challenger) do |f| %>
  <% if @challenger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@challenger.errors.count, "error") %> prohibited this challenger from being saved:</h2>

      <ul>
      <% @challenger.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :challenge_id %><br>
    <%= f.number_field :challenge_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/Admin/challengers/edit.html.erb
<h1>Editing challenger</h1>

<%= render 'form' %>

<%= link_to 'Show', @challenger %> |
<%= link_to 'Back', challengers_path %>

app/views/Admin/challengers/index.html.erb
<h1>Listing challengers</h1>

<table>
  <thead>
    <tr>
      <th>Challenge</th>
      <th>User</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @challengers.each do |challenger| %>
      <tr>
        <td><%= challenger.challenge_id %></td>
        <td><%= challenger.user_id %></td>
        <td><%= challenger.status %></td>
        <td><%= link_to 'Show', challenger %></td>
        <td><%= link_to 'Edit', edit_challenger_path(challenger) %></td>
        <td><%= link_to 'Destroy', challenger, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Challenger', new_challenger_path %>

app/views/Admin/challengers/new.html.erb
<h1>New challenger</h1>

<%= render 'form' %>

<%= link_to 'Back', challengers_path %>

app/views/Admin/challengers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Challenge:</strong>
  <%= @challenger.challenge_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @challenger.user_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @challenger.status %>
</p>

<%= link_to 'Edit', edit_challenger_path(@challenger) %> |
<%= link_to 'Back', challengers_path %>