config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users

    resources :friendships

    resources :challengers

    resources :challenges

    resources :places

    resources :activities

    resources :activity_types

    resources :team_members

    resources :teams
  end

  devise_for :logins, controllers: {
      sessions: 'login/sessions',
      registrations: 'login/registrations',
      passwords: 'login/passwords'
  }

  resources :activities
  resources :challenges
  resources :users, :except => [:index, :delete]
  resources :places, :except => [:edit, :update, :delete]
  resources :friendships, :except => [:new, :update]
  resources :teams
  resources :team_members, :except => [:index, :new, :create, :edit, :update]
  get 'team_member/new/:id' => 'team_members#new', as: 'new_team_member'
  post 'team_member/new/:id' => 'team_members#create', as: 'team_members'
  resources :challengers, :except => [:index, :new, :create, :edit, :update]
  get 'challenger/new/:id' => 'challengers#new', as: 'new_challenger'
  post 'challenger/new/:id' => 'challengers#create', as: 'challengers'

  get 'search' => 'welcome#search', as: 'search'
  get 'dashboard' => 'users#dashboard', as: 'dashboard'
  get 'livefeed' => 'welcome#livefeed', as: 'livefeed'
  get 'leaderboards' => 'welcome#leaderboards'
  get 'popular_sports' => 'welcome#popular_sports'
  get 'popular_places' => 'welcome#popular_places'
  get 'about' => 'welcome#about'
  get 'privacy' => 'welcome#privacy'
  get 'contact' => 'welcome#contact'
  get 'access_denied' => 'welcome#access_denied', as: 'access_denied'
  get 'not_found' => 'welcome#not_found', as: 'not_found'

  root 'welcome#index'

end

app/controllers/Admin/activity_types_controller.rb
class Admin::ActivityTypesController < AdminController
  before_action :set_activity_type, only: [:show, :edit, :update, :destroy]

  def index
    @activity_types = ActivityType.all
    respond_with(@activity_types)
  end

  def show
    respond_with(@activity_type)
  end

  def new
    @activity_type = ActivityType.new
    respond_with(@activity_type)
  end

  def edit
  end

  def create
    @activity_type = ActivityType.new(activity_type_params)
    @activity_type.save
    respond_with(@activity_type)
  end

  def update
    @activity_type.update(activity_type_params)
    respond_with(@activity_type)
  end

  def destroy
    @activity_type.destroy
    respond_with(@activity_type)
  end

  private
    def set_activity_type
      @activity_type = ActivityType.find(params[:id])
    end

    def activity_type_params
      params.require(:activity_type).permit(:name)
    end
end

app/controllers/activity_types_controller.rb
class ActivityTypesController < ApplicationController
  before_action :set_activity_type, only: [:show, :edit, :update, :destroy]

  def index
    @activity_types = ActivityType.all
    respond_with(@activity_types)
  end

  def show
    respond_with(@activity_type)
  end

  def new
    @activity_type = ActivityType.new
    respond_with(@activity_type)
  end

  def edit
  end

  def create
    @activity_type = ActivityType.new(activity_type_params)
    @activity_type.save
    respond_with(@activity_type)
  end

  def update
    @activity_type.update(activity_type_params)
    respond_with(@activity_type)
  end

  def destroy
    @activity_type.destroy
    respond_with(@activity_type)
  end

  private
    def set_activity_type
      @activity_type = ActivityType.find(params[:id])
    end

    def activity_type_params
      params.require(:activity_type).permit(:name)
    end
end

app/helpers/activity_types_helper.rb
module ActivityTypesHelper
end

app/views/Admin/activity_types/_form.html.erb
<%= form_for(@activity_type) do |f| %>
  <% if @activity_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity_type.errors.count, "error") %> prohibited this activity_type from being saved:</h2>

      <ul>
      <% @activity_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/Admin/activity_types/edit.html.erb
<h1>Editing activity_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity_type %> |
<%= link_to 'Back', activity_types_path %>

app/views/Admin/activity_types/index.html.erb
<h1>Listing activity_types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activity_types.each do |activity_type| %>
      <tr>
        <td><%= activity_type.name %></td>
        <td><%= link_to 'Show', activity_type %></td>
        <td><%= link_to 'Edit', edit_activity_type_path(activity_type) %></td>
        <td><%= link_to 'Destroy', activity_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity type', new_activity_type_path %>

app/views/Admin/activity_types/new.html.erb
<h1>New activity_type</h1>

<%= render 'form' %>

<%= link_to 'Back', activity_types_path %>

app/views/Admin/activity_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @activity_type.name %>
</p>

<%= link_to 'Edit', edit_activity_type_path(@activity_type) %> |
<%= link_to 'Back', activity_types_path %>