config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users

    resources :friendships

    resources :challengers

    resources :challenges

    resources :places

    resources :activities

    resources :activity_types

    resources :team_members

    resources :teams
  end

  devise_for :logins, controllers: {
      sessions: 'login/sessions',
      registrations: 'login/registrations',
      passwords: 'login/passwords'
  }

  resources :activities
  resources :challenges
  resources :users, :except => [:index, :delete]
  resources :places, :except => [:edit, :update, :delete]
  resources :friendships, :except => [:new, :update]
  resources :teams
  resources :team_members, :except => [:index, :new, :create, :edit, :update]
  get 'team_member/new/:id' => 'team_members#new', as: 'new_team_member'
  post 'team_member/new/:id' => 'team_members#create', as: 'team_members'
  resources :challengers, :except => [:index, :new, :create, :edit, :update]
  get 'challenger/new/:id' => 'challengers#new', as: 'new_challenger'
  post 'challenger/new/:id' => 'challengers#create', as: 'challengers'

  get 'search' => 'welcome#search', as: 'search'
  get 'dashboard' => 'users#dashboard', as: 'dashboard'
  get 'livefeed' => 'welcome#livefeed', as: 'livefeed'
  get 'leaderboards' => 'welcome#leaderboards'
  get 'popular_sports' => 'welcome#popular_sports'
  get 'popular_places' => 'welcome#popular_places'
  get 'about' => 'welcome#about'
  get 'privacy' => 'welcome#privacy'
  get 'contact' => 'welcome#contact'
  get 'access_denied' => 'welcome#access_denied', as: 'access_denied'
  get 'not_found' => 'welcome#not_found', as: 'not_found'

  root 'welcome#index'

end

app/models/place.rb
class Place < ActiveRecord::Base
  has_many :activities
  has_many :challenges
  has_many :users, through: :activities

  validates :name, :coordinate_lat, :coordinate_long, presence: true
  validates :name, uniqueness: true


end

app/controllers/Admin/places_controller.rb
class Admin::PlacesController < AdminController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  def index
    @places = Place.all
    respond_with(@places)
  end

  def show
    respond_with(@place)
  end

  def new
    @place = Place.new
    respond_with(@place)
  end

  def edit
  end

  def create
    @place = Place.new(place_params)
    @place.save
    respond_with(@place)
  end

  def update
    @place.update(place_params)
    respond_with(@place)
  end

  def destroy
    @place.destroy
    respond_with(@place)
  end

  private
    def set_place
      @place = Place.find(params[:id])
    end

    def place_params
      params.require(:place).permit(:name, :coordinate_lat, :coordinate_long)
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  respond_to :html, :json
  before_action :set_place, only: [:show]
  skip_before_action :is_logged_in, only: [:show]

  def index
    @places = Place.all
    respond_with(@places)
  end

  def show
    respond_with(@place)
  end

  def new
    @place = Place.new
    respond_with(@place)
  end

  def create
    @place = Place.new(place_params)
    @place.save
    respond_with(@place)
  end

  private
    def set_place
      @place = Place.find(params[:id])
    end

    def place_params
      params.require(:place).permit(:name, :coordinate_lat, :coordinate_long)
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
    <% if @place.errors.any? %>
        <div class="alert alert-danger alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <strong>Errors!</strong>
          <ul>
            <% @place.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

  <div class="form-group">
    <%= f.label :name, class: 'form-label' %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :coordinate_lat, class: 'form-label' %><br>
    <%= f.text_field :coordinate_lat, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :coordinate_long, class: 'form-label' %><br>
    <%= f.text_field :coordinate_long, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit nil, class: 'btn btn-primary' %>
    <%= link_to 'Back', places_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<div class="page-header">
  <h1><i class="glyphicon glyphicon-map-marker"></i> Places</h1>
</div>

<p><%= link_to 'Add Place', new_place_path, class: 'btn btn-primary' %></p>

<div class="table-responsive">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Coordinate lat</th>
      <th>Coordinate long</th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= link_to place.name, place %></td>
        <td><%= place.coordinate_lat %></td>
        <td><%= place.coordinate_long %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/places/new.html.erb
<div class="page-header">
  <h1><i class="glyphicon glyphicon-map-marker"></i> New Place</h1>
</div>

<%= render 'form' %>

app/views/places/show.html.erb
<div class="page-header">
  <h1><i class="glyphicon glyphicon-map-marker"></i> <%= @place.name %></h1>
</div>

<% if login_signed_in? %>
<p><%= link_to 'Back', places_path, class: 'btn btn-default' %></p>
<% end %>

<div class="table-responsive">
  <table class="table table-striped table-bordered">
        <tr>
          <td><strong>Coordinate Lat:</strong></td>
          <td><%= @place.coordinate_lat %></td>
        </tr>
        <tr>
          <td><strong>Coordinate Long:</strong></td>
          <td><%= @place.coordinate_long %></td>
        </tr>
  </table>
</div>

<div id="gmap"></div>

<script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
<script>
    function initialize() {
        var myLatlng = new google.maps.LatLng(<%= @place.coordinate_lat.to_s %>,<%= @place.coordinate_long.to_s %>);
        var mapOptions = {
            zoom: 15,
            center: myLatlng
        }
        var map = new google.maps.Map(document.getElementById("gmap"), mapOptions);

        var marker = new google.maps.Marker({
            position: myLatlng,
            map: map,
            title: '<%= @place.name %>',
            zIndex: 999
        });

        <% @current_user.friends_activities.each do |activity| %>
        var infowindow<%= activity.id %> = new google.maps.InfoWindow({
            content: '<div id="content">'+
                    '<div id="siteNotice">'+
                    '</div>'+
                    '<p id="firstHeading" class="firstHeading"><strong>Activity:</strong> <%= link_to activity.name, activity %></p>'+
                    '<div id="bodyContent">'+
                    '<p><strong>Athlete:</strong> <%= link_to activity.user.name, activity.user %></p>'+
                    '</ul>'+
                    '</div>'+
                    '</div>'
        });
        var marker<%= activity.id %> = new google.maps.Marker({
            position: new google.maps.LatLng(<%= activity.place.coordinate_lat.to_s %>,<%= activity.place.coordinate_long.to_s %>),
            map: map,
            icon: 'http://localhost:3000/images/marker.png'
        });
        google.maps.event.addListener(marker<%= activity.id %>, 'click', function() {
            infowindow<%= activity.id %>.open(map,marker<%= activity.id %>);
        });
        <% end %>
    }
    google.maps.event.addDomListener(window, "load", initialize);

    $(document).ready(function(){ initialize(); });
</script>